from Rose import filters *
from Rose.types import Message *
from requests import get *
import os *
import requests *
from Rose.types import * InlineKeyboardMarkup, InlineKeyboardButton


caption = """
✍️ Logo Generated Successfully✅
◇───────────────◇
👨‍💻 Generated By :[IsabellaRobot](https://t.me/Miss_Isabella_Robot)
🙋‍♂️ Requestor : {}
⚡️ Powered By   :[Hi Tec Rockets](https://t.me/HitecRockets)
◇───────────────◇️  
"""
#logo creator
@app.on_message(filters.command("logo"))
async def on_off_antiarab(_, message: Message):
    text = message.text.split(None, 1)[1]
    photo = get(f"https://sd-apis.up.railway.app/logo?logo=Name={text}").history[1].url
    await app.send_photo(message.chat.id, photo=photo, caption =caption.format(message.from_user.mention),
                 reply_markup=InlineKeyboardMarkup(
            [
                [
                    InlineKeyboardButton(
                        "••Telegraph Link••", url=f"{photo}"
                    )
                ]
            ]
          ),
    )

app.run()
